import { NextResponse } from "next/server";
import { db } from "@/db";
import { categories, products, reviews } from "@/db/schema";
import { sql } from "drizzle-orm";

export async function POST() {
  try {
    // Clear existing data
    await db.execute(sql`TRUNCATE reviews, cart_items, orders, products, categories RESTART IDENTITY CASCADE`);

    const cats = await db
      .insert(categories)
      .values([
        { name: "Beach & Island Getaways", slug: "beach-island", description: "Pristine shores, turquoise waters, and endless relaxation", image: "https://images.pexels.com/photos/1320686/pexels-photo-1320686.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200" },
        { name: "European Adventures", slug: "european-adventures", description: "Historic cities, stunning architecture, and rich culture", image: "https://images.pexels.com/photos/16922421/pexels-photo-16922421.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200" },
        { name: "Mountain & Hiking Expeditions", slug: "mountain-hiking", description: "Conquer peaks and discover breathtaking alpine scenery", image: "https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200" },
        { name: "Safari & Wildlife", slug: "safari-wildlife", description: "Witness nature's most magnificent creatures up close", image: "https://images.pexels.com/photos/28157155/pexels-photo-28157155.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200" },
        { name: "Cruise & Ocean Voyages", slug: "cruise-ocean", description: "Luxury at sea with world-class destinations", image: "https://images.pexels.com/photos/33270055/pexels-photo-33270055.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200" },
        { name: "Cultural & Heritage Tours", slug: "cultural-heritage", description: "Immerse yourself in traditions and ancient wonders", image: "https://images.pexels.com/photos/16226627/pexels-photo-16226627.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200" },
      ])
      .returning();

    const prods = await db
      .insert(products)
      .values([
        { name: "Maldives Overwater Villa Escape", slug: "maldives-overwater-villa", description: "Experience paradise at its finest with a 7-night stay in a private overwater villa. Wake up to crystal-clear lagoon views, enjoy world-class snorkeling right from your deck, and unwind with spa treatments overlooking the Indian Ocean.", shortDescription: "7 nights in a private overwater villa with all-inclusive dining & spa", price: "4299.00", originalPrice: "5499.00", images: ["https://images.pexels.com/photos/1320686/pexels-photo-1320686.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/9080921/pexels-photo-9080921.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/14923418/pexels-photo-14923418.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/6875499/pexels-photo-6875499.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[0].id, duration: "7 Nights / 8 Days", location: "Maldives", travelType: "couple", highlights: ["Private overwater villa","All-inclusive dining","Sunset dolphin cruise","Spa treatments","Snorkeling excursions","Seaplane transfers"], included: ["Return seaplane transfers","All meals & premium beverages","Daily spa credit ($150)","Snorkeling gear","Sunset cruise","Airport lounge access"], featured: true, bestSeller: true, maxGuests: 4, rating: "4.9", reviewCount: 127 },
        { name: "Bali Family Paradise Retreat", slug: "bali-family-paradise", description: "Create unforgettable family memories in Bali with this 10-day adventure.", shortDescription: "10-day family adventure with private villa, cultural tours & activities", price: "3199.00", originalPrice: "3899.00", images: ["https://images.pexels.com/photos/6016924/pexels-photo-6016924.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/23696830/pexels-photo-23696830.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/14923418/pexels-photo-14923418.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/23696838/pexels-photo-23696838.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[0].id, duration: "10 Nights / 11 Days", location: "Bali, Indonesia", travelType: "family", highlights: ["Private villa with pool","Cooking class","Temple tours","White water rafting","Rice terrace trek","Cliffside dinner"], included: ["Airport transfers","Breakfast daily","5 guided excursions","Cooking class","Rafting adventure","Kids' activity program"], featured: true, bestSeller: false, maxGuests: 8, rating: "4.8", reviewCount: 89 },
        { name: "Santorini Sunset Romance", slug: "santorini-sunset-romance", description: "Fall in love all over again on the magical island of Santorini.", shortDescription: "5-night romantic escape with cave suite, wine tasting & sunset cruise", price: "2899.00", originalPrice: "3299.00", images: ["https://images.pexels.com/photos/5785080/pexels-photo-5785080.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/31587579/pexels-photo-31587579.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/30794940/pexels-photo-30794940.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/28945727/pexels-photo-28945727.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[0].id, duration: "5 Nights / 6 Days", location: "Santorini, Greece", travelType: "couple", highlights: ["Cave suite with caldera views","Sunset catamaran cruise","Wine tasting experience","Couples spa treatment","Oia village tour","Helicopter tour option"], included: ["Airport transfers","Daily breakfast","Wine tasting tour","Sunset cruise","Spa session for two","Welcome champagne"], featured: false, bestSeller: true, maxGuests: 2, rating: "4.9", reviewCount: 203 },
        { name: "Grand European Discovery", slug: "grand-european-discovery", description: "Embark on the ultimate European journey spanning 14 days across 5 iconic cities.", shortDescription: "14-day journey through 5 European capitals with first-class rail travel", price: "5999.00", originalPrice: "7299.00", images: ["https://images.pexels.com/photos/16922421/pexels-photo-16922421.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/18815996/pexels-photo-18815996.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/18688136/pexels-photo-18688136.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/16857488/pexels-photo-16857488.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[1].id, duration: "14 Nights / 15 Days", location: "Paris, Rome, Barcelona, Vienna, Amsterdam", travelType: "solo", highlights: ["5 iconic cities","First-class rail pass","Michelin dinner","Private museum tours","Seine river cruise","Wine country day trip"], included: ["First-class Eurail pass","Boutique hotel stays","Daily breakfast","8 guided tours","Michelin dinner","Travel insurance"], featured: true, bestSeller: true, maxGuests: 6, rating: "4.7", reviewCount: 156 },
        { name: "Prague & Budapest Twin City Break", slug: "prague-budapest-twin-city", description: "Discover two of Central Europe's most enchanting capitals.", shortDescription: "6-night twin city adventure exploring Prague & Budapest", price: "1899.00", originalPrice: "2299.00", images: ["https://images.pexels.com/photos/18192481/pexels-photo-18192481.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/18815996/pexels-photo-18815996.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/16922421/pexels-photo-16922421.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/22619624/pexels-photo-22619624.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[1].id, duration: "6 Nights / 7 Days", location: "Prague & Budapest", travelType: "couple", highlights: ["Charles Bridge sunrise tour","Thermal bath experience","Danube dinner cruise","Ruin bar tour","Castle District walk","Beer tasting"], included: ["Train transfer between cities","Boutique hotels","Daily breakfast","Walking tours","Danube cruise","Thermal bath entry"], featured: false, bestSeller: false, maxGuests: 4, rating: "4.8", reviewCount: 94 },
        { name: "Nepal Everest Base Camp Trek", slug: "nepal-everest-base-camp", description: "The adventure of a lifetime awaits on this legendary 14-day trek to Everest Base Camp.", shortDescription: "14-day guided trek to Everest Base Camp with experienced Sherpa guides", price: "2499.00", originalPrice: "2999.00", images: ["https://images.pexels.com/photos/11930659/pexels-photo-11930659.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/9629654/pexels-photo-9629654.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/17317399/pexels-photo-17317399.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[2].id, duration: "14 Nights / 15 Days", location: "Nepal, Himalayas", travelType: "solo", highlights: ["Everest Base Camp","Kala Patthar sunrise","Sherpa villages","Namche Bazaar","Suspension bridges","Himalayan panoramas"], included: ["Experienced Sherpa guide","Porter service","All meals on trek","Teahouse stays","Permits & fees","Celebratory dinner"], featured: true, bestSeller: false, maxGuests: 12, rating: "4.9", reviewCount: 78 },
        { name: "Canadian Rockies Family Adventure", slug: "canadian-rockies-family", description: "Discover the raw beauty of the Canadian Rockies on this 8-day family adventure.", shortDescription: "8-day family mountain adventure in Banff & Jasper National Parks", price: "3599.00", originalPrice: "4199.00", images: ["https://images.pexels.com/photos/33310482/pexels-photo-33310482.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/6016924/pexels-photo-6016924.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/9629654/pexels-photo-9629654.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[2].id, duration: "8 Nights / 9 Days", location: "Banff & Jasper, Canada", travelType: "family", highlights: ["Banff Gondola ride","Lake Louise visit","Wildlife spotting","River rafting","Helicopter flight","Campfire evenings"], included: ["Mountain lodge accommodation","Daily breakfast & dinner","Park passes","Guided hikes","Rafting excursion","Kids' adventure program"], featured: false, bestSeller: true, maxGuests: 8, rating: "4.8", reviewCount: 112 },
        { name: "Tanzania Great Migration Safari", slug: "tanzania-great-migration", description: "Witness one of nature's most awe-inspiring spectacles — the Great Migration across the Serengeti.", shortDescription: "10-day luxury safari witnessing the Great Migration in the Serengeti", price: "6499.00", originalPrice: "7999.00", images: ["https://images.pexels.com/photos/28157155/pexels-photo-28157155.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/36702538/pexels-photo-36702538.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/9185432/pexels-photo-9185432.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/19281386/pexels-photo-19281386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[3].id, duration: "10 Nights / 11 Days", location: "Tanzania, East Africa", travelType: "couple", highlights: ["Great Migration viewing","Ngorongoro Crater","Hot air balloon","Maasai village visit","Big Five spotting","Luxury tented camps"], included: ["Luxury tented accommodation","All meals & drinks","Game drives","Balloon safari","Park fees","Internal flights"], featured: true, bestSeller: true, maxGuests: 6, rating: "5.0", reviewCount: 67 },
        { name: "Mediterranean Grand Cruise", slug: "mediterranean-grand-cruise", description: "Set sail on a 12-night Mediterranean odyssey visiting 8 stunning ports.", shortDescription: "12-night luxury Mediterranean cruise visiting 8 ports of call", price: "4799.00", originalPrice: "5999.00", images: ["https://images.pexels.com/photos/33270055/pexels-photo-33270055.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/37880222/pexels-photo-37880222.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/24244288/pexels-photo-24244288.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/17712477/pexels-photo-17712477.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[4].id, duration: "12 Nights / 13 Days", location: "Mediterranean Sea", travelType: "family", highlights: ["8 ports of call","Private balcony stateroom","12 dining venues","Luxury spa","Shore excursions","Evening entertainment"], included: ["Balcony stateroom","All meals onboard","Entertainment package","2 shore excursions","Spa credit ($200)","Beverage package"], featured: true, bestSeller: false, maxGuests: 4, rating: "4.7", reviewCount: 189 },
        { name: "Japan Cherry Blossom Cultural Journey", slug: "japan-cherry-blossom", description: "Experience the magic of Japan during sakura season on this meticulously curated 12-day cultural journey.", shortDescription: "12-day cultural journey through Japan during cherry blossom season", price: "5299.00", originalPrice: "6499.00", images: ["https://images.pexels.com/photos/16226627/pexels-photo-16226627.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/20817306/pexels-photo-20817306.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/36353249/pexels-photo-36353249.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/31761848/pexels-photo-31761848.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[5].id, duration: "12 Nights / 13 Days", location: "Tokyo, Kyoto, Nara, Hiroshima", travelType: "solo", highlights: ["Cherry blossom viewing","Tea ceremony","Ryokan stay","Geisha district tour","Shinkansen travel","Sushi-making class"], included: ["Boutique hotels & ryokan","Japan Rail Pass","Daily breakfast","8 cultural experiences","Tea ceremony","Airport transfers"], featured: true, bestSeller: true, maxGuests: 10, rating: "4.9", reviewCount: 143 },
        { name: "Costa Rica Solo Explorer", slug: "costa-rica-solo-explorer", description: "Embrace the Pura Vida lifestyle on this thrilling 9-day solo adventure through Costa Rica.", shortDescription: "9-day solo adventure through Costa Rica's rainforests & volcanoes", price: "1999.00", originalPrice: "2499.00", images: ["https://images.pexels.com/photos/6016924/pexels-photo-6016924.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/23696830/pexels-photo-23696830.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/17317399/pexels-photo-17317399.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[2].id, duration: "9 Nights / 10 Days", location: "Costa Rica", travelType: "solo", highlights: ["Zip-lining","Volcano hiking","Surfing lessons","Wildlife spotting","Hot springs","Cloud forest walk"], included: ["Eco-lodge stays","Daily breakfast","6 guided activities","Surf lesson","National park fees","Airport transfers"], featured: false, bestSeller: false, maxGuests: 1, rating: "4.6", reviewCount: 62 },
        { name: "Amalfi Coast Luxury Escape", slug: "amalfi-coast-luxury", description: "Indulge in la dolce vita along Italy's most glamorous coastline.", shortDescription: "7-night luxury Italian coastal escape with private boat tours & cooking classes", price: "3899.00", originalPrice: "4599.00", images: ["https://images.pexels.com/photos/16857488/pexels-photo-16857488.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/18688136/pexels-photo-18688136.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/18192481/pexels-photo-18192481.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200","https://images.pexels.com/photos/22619624/pexels-photo-22619624.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"], categoryId: cats[1].id, duration: "7 Nights / 8 Days", location: "Amalfi Coast, Italy", travelType: "couple", highlights: ["Positano cliffside hotel","Private boat tour","Cooking class","Pompeii visit","Limoncello tasting","Capri day trip"], included: ["Boutique hotel stay","Daily breakfast","Private boat tour","Cooking class","Pompeii guided tour","Airport transfers"], featured: false, bestSeller: true, maxGuests: 4, rating: "4.8", reviewCount: 176 },
      ])
      .returning();

    // Seed reviews
    const reviewsData = [
      { productId: prods[0].id, authorName: "Sarah & James Mitchell", rating: 5, title: "Beyond our wildest dreams", content: "This trip exceeded every expectation. The overwater villa was absolutely stunning!", travelDate: "March 2025", travelType: "Couple" },
      { productId: prods[0].id, authorName: "Elena Rodriguez", rating: 5, title: "Pure paradise", content: "Hands down the most beautiful destination I've visited. The snorkeling was incredible!", travelDate: "January 2025", travelType: "Couple" },
      { productId: prods[1].id, authorName: "The Williams Family", rating: 5, title: "Best family vacation ever!", content: "Our kids still talk about this trip daily. The cooking class was a highlight!", travelDate: "July 2025", travelType: "Family" },
      { productId: prods[2].id, authorName: "Mark & Lisa Johnson", rating: 5, title: "The perfect anniversary trip", content: "We chose this for our 10th anniversary and it was absolutely perfect.", travelDate: "September 2025", travelType: "Couple" },
      { productId: prods[3].id, authorName: "Alex Thompson", rating: 5, title: "Life-changing journey", content: "As a solo traveler, the itinerary was so well planned that I met amazing people at every stop.", travelDate: "June 2025", travelType: "Solo" },
      { productId: prods[4].id, authorName: "Tom & Amy Richards", rating: 5, title: "Hidden gems of Europe", content: "Prague and Budapest blew us away. The Danube dinner cruise was one of the most beautiful things we've ever seen.", travelDate: "April 2025", travelType: "Couple" },
      { productId: prods[5].id, authorName: "Michael Torres", rating: 5, title: "Achievement unlocked!", content: "Standing at Everest Base Camp was the most profound experience of my life.", travelDate: "November 2025", travelType: "Solo" },
      { productId: prods[6].id, authorName: "The Garcia Family", rating: 5, title: "Nature at its absolute best", content: "We saw bears, elk, and even a moose! Lake Louise was even more beautiful than the photos.", travelDate: "August 2025", travelType: "Family" },
      { productId: prods[7].id, authorName: "Christine & Robert Bell", rating: 5, title: "Once in a lifetime", content: "Watching thousands of wildebeest cross the Mara River was like watching a nature documentary in real life.", travelDate: "July 2025", travelType: "Couple" },
      { productId: prods[8].id, authorName: "Patricia & Harold Moore", rating: 5, title: "Floating luxury palace", content: "Everything about this cruise was first-class. We tried all 12 restaurants!", travelDate: "September 2025", travelType: "Family" },
      { productId: prods[9].id, authorName: "Maria Santos", rating: 5, title: "Japan during sakura is MAGIC", content: "Every day was more beautiful than the last. The tea ceremony was a profound experience.", travelDate: "April 2025", travelType: "Solo" },
      { productId: prods[10].id, authorName: "Ryan Douglas", rating: 5, title: "Pure adventure", content: "Costa Rica was perfect for a solo traveler. The zip-lining was exhilarating!", travelDate: "February 2025", travelType: "Solo" },
      { productId: prods[11].id, authorName: "Isabella & Marco Bianchi", rating: 5, title: "La dolce vita indeed!", content: "The cooking class with Nonna Maria was unforgettable. Her pasta recipe is now a family heirloom.", travelDate: "June 2025", travelType: "Couple" },
    ];

    await db.insert(reviews).values(reviewsData);

    return NextResponse.json({ success: true, categories: cats.length, products: prods.length, reviews: reviewsData.length });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Seed failed" }, { status: 500 });
  }
}
